# Site Information
site_name: Fluid Numerics Galapagos
site_author: Fluid Numerics
site_dir: public
site_url: ""
repo_name: GitHub/fluidnumerics/galapagos
repo_url: https://github.com/fluidnumerics/galapagos
edit_uri: edit/master/docs

# Directory where site content is located
docs_dir: docs

# Site navigation
nav:
  - Home: README.md
  - Available Hardware & Software: available-resources.md

  - User Onboarding:
    - Onboarding overview: onboarding/overview.md
    - Obtaining an account: onboarding/getting_an_account.md
    - Using SSH Keys: onboarding/ssh_keys.md

  - Getting work done:
    - Command Line Interface:
      - Selecting Hardware: getting-work-done/cli/selecting_hardware.md
      - Running Batch Jobs: getting-work-done/cli/batch_jobs.md
      - Running Interactive Jobs: getting-work-done/cli/interactive_jobs.md
      - Software : getting-work-done/cli/software.md
      - Jupyter Notebooks: getting-work-done/cli/jupyter-notebooks.md

    - Web interface: getting-work-done/webinterface/overview.md
      # - File Manager: getting-work-done/webinterface/filemanager.md
      # - Terminal: getting-work-done/webinterface/terminal.md
    #   - Job Composer: getting-work-done/webinterface/jobcomposer.md
    #   - Remote Desktop: getting-work-done/webinterface/remote-desktop.md
    #   - Jupyter Notebooks: getting-work-done/webinterface/jupyter-notebook.md

  - GPU Programming:
    - Targeting GPU Architectures: gpu/architecture_codes.md
    - Working with MI300A: gpu/working_with_mi300a.md
  #- Tutorials:

  - Contact Support: contact-us.md


theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    - scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    - scheme: default
      primary: black
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html

plugins: []
